<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOYltFON\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOYltFON/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOYltFON.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOYltFON\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOYltFON\App_KernelDevDebugContainer([
    'container.build_hash' => 'OYltFON',
    'container.build_id' => '96e58ea0',
    'container.build_time' => 1648461404,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOYltFON');
